version: "3"

services:
  webapp:
    image: efforteo.webapp
    build: ../src/Efforteo.WebApp/efforteo-webapp
    ports:
      - 4200:4200
      - 49152:49152
    restart: on-failure

  auth-db:
    image: mongo:3.6
    ports:
      - '27217:27017'
    restart: on-failure

  accounts-db:
    image: mongo:3.6
    ports:
      - '27317:27017'
    restart: on-failure

  activities-db:
    image: mongo:3.6
    ports:
      - '27017:27017'
    restart: on-failure

  stats-db:
    image: mongo:3.6
    ports:
      - '27117:27017'
    restart: on-failure

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: on-failure

  api-service:
    image: efforteo.services.api
    build: ../src/Efforteo.Services.Api
    depends_on:
      - authentication-service
      - accounts-service
      - activities-service
    ports:
      - '5000:5000'
      - '5001:5001'
    restart: on-failure

  authentication-service:
    image: efforteo.services.authentication
    build: ../src/Efforteo.Services.Authentication
    depends_on:
      - auth-db
      - rabbitmq
    links:
      - rabbitmq
      - auth-db
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  accounts-service:
    image: efforteo.services.accounts
    build: ../src/Efforteo.Services.Accounts
    depends_on:
      - accounts-db
      - rabbitmq
    links:
      - rabbitmq
      - accounts-db
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  activities-service:
    image: efforteo.services.activities
    build: ../src/Efforteo.Services.Activities
    depends_on:
      - activities-db
      - rabbitmq
    links:
      - rabbitmq
      - activities-db
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  stats-service:
    image: efforteo.services.stats
    build: ../src/Efforteo.Services.Stats
    depends_on:
      - stats-db
      - rabbitmq
    links:
      - rabbitmq
      - stats-db
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
