version: "3"

services:
  webapp:
    image: efforteo.webapp
    build: ../src/Efforteo.WebApp/efforteo-webapp
    ports:
      - 4200:4200
      - 49152:49152

  auth-db:
    image: mongo:3.6
    volumes:
      - './data_auth:/data/db'
    ports:
      - '27217:27017'

  accounts-db:
    image: mongo:3.6
    volumes:
      - './data_acc:/data/db'
    ports:
      - '27317:27017'

  activities-db:
    image: mongo:3.6
    volumes:
      - './data_act:/data/db'
    ports:
      - '27017:27017'

  stats-db:
    image: mongo:3.6
    volumes:
      - './data_stat:/data/db'
    ports:
      - '27117:27017'

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./data:/var/lib/rabbitmq:rw
      - ./definitions.json:/opt/definitions.json:ro
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro

  api-service:
    image: efforteo.services.api
    build: ../src/Efforteo.Services.Api
    depends_on:
      - authentication-service
      - accounts-service
      - activities-service
    ports:
      - '5000:5000'
      - '5001:5001'

  authentication-service:
    image: efforteo.services.authentication
    build: ../src/Efforteo.Services.Authentication
    depends_on:
      - auth-db
      - rabbitmq
    links:
      - rabbitmq
      - auth-db

  accounts-service:
    image: efforteo.services.accounts
    build: ../src/Efforteo.Services.Accounts
    depends_on:
      - accounts-db
      - rabbitmq
    links:
      - rabbitmq
      - accounts-db
  
  activities-service:
    image: efforteo.services.activities
    build: ../src/Efforteo.Services.Activities
    depends_on:
      - activities-db
      - rabbitmq
    links:
      - rabbitmq
      - activities-db

  stats-service:
    image: efforteo.services.stats
    build: ../src/Efforteo.Services.Stats
    depends_on:
      - stats-db
      - rabbitmq
    links:
      - rabbitmq
      - stats-db
