version: "3"

services:
  webapp:
    image: efforteo.webapp
    build: ../src/Efforteo.WebApp/efforteo-webapp
    ports:
      - 4200:4200
      - 49152:49152
    #volumes:
    #  - '.:/usr/src/app'
    #  - '/usr/src/app/node_modules'
  mongo:
    image: mongo:3.6
    volumes:
      - './data:/data/db'
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./data:/var/lib/rabbitmq:rw
      - ./definitions.json:/opt/definitions.json:ro
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro

  api-service:
    image: efforteo.services.api
    build: ../src/Efforteo.Services.Api
    depends_on:
      - authentication-service
      - accounts-service
      - activities-service
    ports:
      - '5000:5000'
      - '5001:5001'
  
  activities-service:
    image: efforteo.services.activities
    build: ../src/Efforteo.Services.Activities
    depends_on:
      - mongo
      - rabbitmq
    links:
      - rabbitmq
      - mongo

  authentication-service:
    image: efforteo.services.authentication
    build: ../src/Efforteo.Services.Authentication
    depends_on:
      - mongo
      - rabbitmq
    links:
      - rabbitmq
      - mongo

  accounts-service:
    image: efforteo.services.accounts
    build: ../src/Efforteo.Services.Accounts
    depends_on:
      - mongo
      - rabbitmq
    links:
      - rabbitmq
      - mongo

  stats-service:
    image: efforteo.services.stats
    build: ../src/Efforteo.Services.Stats
    depends_on:
      - mongo
      - rabbitmq
    links:
      - rabbitmq
      - mongo
