version: "3.4"

services:
  nosql.data:
    image: mongo
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'

  api:
    build: ../src/Efforteo.Api
    restart: on-failure
    depends_on:
      - nosql.data
      - rabbitmq
    ports:
      - '5000:5000'

  activities-service:
    build: ../src/Efforteo.Services.Activities
    restart: on-failure
    depends_on:
      - nosql.data
      - rabbitmq
    ports:
      - '5010:5000'

  identity-service:
    build: ../src/Efforteo.Services.Identity
    restart: on-failure
    depends_on:
      - nosql.data
      - rabbitmq
    ports:
     - '5020:5000'
